### ISSUE TITLE
When payment fails, payment button does not reset

### ISSUE THREAD

**Issue by Kukanani** [gu-app-club/save-the-net#4]
I entered my payment information incorrectly. The site informed me of this, but the button did not reset to an active state, so I was unable to pay after updating the information. I ended up re-writing my letter.

**Comment by Flaque** [comment]
Whoops! I'll fix this, hold on <3 Thanks for letting us know!

**Comment by Flaque** [comment]
Fixed! However, at the moment all cards except the test card "4242 4242 4242 4242" will fail because we're still in "testing" phase and we don't yet want to charge people if we're not 100% sure everythings working.
